
#ifndef __VERSION_H_INCLUDED__
#define __VERSION_H_INCLUDED__

#define NETNSEXEC_VERSION_MAJOR     (0)
#define NETNSEXEC_VERSION_MINOR     (1)
#define NETNSEXEC_VERSION_PATCH     (0)

#endif  // __VERSION_H_INCLUDED__
